#!/bin/bash

SCRIPT=`readlink -f "$0"`
SCRIPT_PATH=`dirname "$SCRIPT"`
source $SCRIPT_PATH/venv
PYTHON=`which python3`

# boot the web app
nohup $PYTHON -m biblicity.app >>$SCRIPT_PATH/var/biblicity.app.log 2>&1 &
echo "$!" >$SCRIPT_PATH/var/biblicity.app.pid


